### ISSUE TITLE
broken tagging

### ISSUE THREAD

**Issue by helloworlddan** [zarplata/concourse-git-bitbucket-pr-resource#22]
Hi!

Your git tagging seems out of place. Somehow almost all your version tags point to the latest source. Hence, almost all your 'versioned' releases and also your image builds on docker hub are the same. You might wanna check this...

<img width="988" alt="screen shot 2019-02-04 at 12 02 50" src="https://user-images.githubusercontent.com/20907695/52204643-0fa0ec80-2875-11e9-8da3-58a3a9ceffc2.png">

**Comment by idr0id** [comment]
Oh well...

**Comment by idr0id** [comment]
I checked the tags, everything's fine. If you care about the same update time, that's only because I make builds and push them at the same time.
