### ISSUE TITLE
quoting issue breaking the resource

### ISSUE THREAD

**Issue by Rukenshia** [zarplata/concourse-git-bitbucket-pr-resource#28]
Hello,

this line breaks the resource:

https://github.com/zarplata/concourse-git-bitbucket-pr-resource/blob/master/assets/check#L79

We had a PR with quotes in it (title: `This is a "test"`). The resource then errors on that line because it is not properly escaped

**Comment by peikk0** [comment]
I think that's been fixed in commit 88b115b2d98a2b609832a78620b12e5fc46f187a.
