### ISSUE TITLE
Builds are running twice

### ISSUE THREAD

**Issue by peikk0** [zarplata/concourse-git-bitbucket-pr-resource#31]
Builds are running twice again, since commit e409aeb4e9118d3818d98f6db0c2dd1713d7f162 I believe because the second build has an `updated_at` attribute added, not present in the first one, that difference triggers a new build.

**Comment by idr0id** [comment]
Oh well, I'll revert that commit now.

**Comment by peikk0** [comment]
It's still happening, we are still seeing a `updated_at` attribute added in the new duplicated version, can you revert 03f87b0e52cba2d1bd19871753a10c3e72955db9 too? That might actually be the one causing it instead of the other commit, or maybe both.

**Comment by peikk0** [comment]
@idr0id can you revert 03f87b0e52cba2d1bd19871753a10c3e72955db9 too please?
