### ISSUE TITLE
Builds are running twice

### ISSUE THREAD

**Issue by heldersepu** [zarplata/concourse-git-bitbucket-pr-resource#34]
Re-raise this as a new issue since the comments on [the closed one](https://github.com/zarplata/concourse-git-bitbucket-pr-resource/issues/31) are not getting any attention.

From @peikk0:
> It's still happening, we are still seeing a updated_at attribute added in the new duplicated version, can you revert 03f87b0 too? That might actually be the one causing it instead of the other commit, or maybe both.

**Comment by idr0id** [comment]
I have no problems with that. Since `check` produced version which included `updated_at` that means `out` must do the same.

**Comment by idr0id** [comment]
Also I commit https://github.com/zarplata/concourse-git-bitbucket-pr-resource/commit/e409aeb4e9118d3818d98f6db0c2dd1713d7f162 back.
