### ISSUE TITLE
branch option may not be working as intented

### ISSUE THREAD

**Issue by RubenJG** [zarplata/concourse-git-bitbucket-pr-resource#35]
When I read about the `branch` option, I thought it would allow me to specify to only listen to PRs created against a specific _target_ branch but when I started testing I noticed that this option only works to specify a _source_ branch.

As an example, if I have a branch `feature/x` and I create a PR `feature/x` --> `develop`. If I specify `develop` in the `branch` option, it never picks up the PR. If I specify `feature/x`, it does pick it up.

Not sure if this is intended functionality. If it is, could a `target_branch` be added as well?

**Comment by danilopopeye** [comment]
> As an example, if I have a branch `feature/x` and I create a PR `feature/x` --> `develop`.
> If I specify `develop` in the `branch` option, it never picks up the PR.

@RubenJG are you using the Server or Cloud version? Just tested against a Server instance and it worker as it should.

**Comment by rubenjimenezGL** [comment]
I was using the Cloud version @danilopopeye

**Comment by RubenJG** [comment]
I was using the Cloud version @danilopopeye

**Comment by danilopopeye** [comment]
> I was using the Cloud version @danilopopeye

hummm, I don't have a Cloud account to test it. 😞 
Can you sanitise a payload JSON and post it here, @RubenJG ?

**Comment by mymasse** [comment]
I ran into this issue and specifying `direction: incoming` fixed the issue.

> direction: Optional. the direction relative to the specified repository, either incoming (destination, e.g. to master) or outgoing (source, e.g. from feature)

**Comment by RubenJG** [comment]
I no longer have access to the code @danilopopeye 🤔 but what you say @mymasse makes sense. I think it would've helped me. Probably #47 fixed this issue 👍
