### ISSUE TITLE
[Question] Rebuild a failed PR

### ISSUE THREAD

**Issue by artamonovkirill** [zarplata/concourse-git-bitbucket-pr-resource#38]
In case of there are 2 active PRs, `trigger-job` starts on a build for a PR that has been built last.
Is there a way to re-trigger a build of a different PR without pushing bogus commits or update PR description?

**Comment by idr0id** [comment]
If you mean "out of the box", then no. But you might
* amend latest commit then force push (no bogus commits)
* temporarily pin the pr resource to a needed version via the [web UI](https://github.com/concourse/concourse/releases/tag/v5.0.0#v500-note-10)
